### ISSUE TITLE
Question: PayPal Rest

### ISSUE THREAD

**Issue by magnessjo** [craftcms/commerce-paypal#1]
The PayPal Rest documentation lists two URLs to complete a PayPal Rest request. A create and execute url.

I am assuming the execute url would be '/actions/commerce/payments/pay', but I not sure what the create payment url is. Would it be the Rest Controller in the commerce-paypal plugin? So something like: '/actions/commerce-paypal/rest/prepare-payment'?

Also, I haven't had time to add subscriptions yet (hopefully soon), but I am wondering if the PayPal Rest gateway will support subscriptions? Their documentation stated that they do support subscriptions, but the commerce gateway documentation stated the Stripe was the 'only first party gateway to support subscriptions'.

Please note: these questions are not urgent. Please answer at your convenience. Thank you in advance for any feedback.

**Comment by andris-sevcenko** [comment]
When you're referencing to "PayPal Rest documentation", what exactly do you mean? If that is a two-step process, that is all handled by `/actions/commerce/payments/pay`.

**Comment by magnessjo** [comment]
@andris-sevcenko,

  Yes it is the two step process.  Thank you I will give it a try with the payments controller.  The PayPal documentation is a little bit of a maze so I think I just got spun around.  

  Thank you for getting back to me.

**Comment by magnessjo** [comment]
@andris-sevcenko,

  Thank you.  Sorry for confusion.  I've ported two sites to commerce 2 and got confused with the PayPal documentation twice. Everything is working as expected.  Thank you.

**Comment by andris-sevcenko** [comment]
It should probably serve us as a pointer where we could work on our documentation, though ;)
