### ISSUE TITLE
PayPal Instant Payment Notifications (IPN) Issue(s)

### ISSUE THREAD

**Issue by 23d1** [craftcms/commerce-paypal#10]
We just received an email from PayPal about failing IPNs (the url referenced has a long list of Craft Commerce and PayPal tags/hashes and so forth, and redirects to a recent order in our system—edited for privacy);

> Please check your server that handles PayPal Instant Payment Notifications (IPN). IPNs sent to the following URL(s) are failing

> `https://askrembla.com/index.php?p=actions%2Fcommerce%2Fpayments%2Fcomplete-payment&commerceTransactionId=<ID>&commerceTransactionHash=<HASH>%0Ahttps%3A%2F%2Faskrembla.com%2Findex.php%3Fp%3Dactions%2Fcommerce%2Fpayments%2Fcomplete-payment&commerceTransactionId=39&commerceTransactionHash=<HASH>7%0Ahttps%3A%2F%2Faskrembla.com%2Findex.php%3Fp%3Dactions%2Fcommerce%2Fpayments%2Fcomplete-payment&commerceTransactionId=42&commerceTransactionHash=<HASH>`

> If you do not recognize this URL, you may be using a service provider that is using IPN on your behalf. Please contact your service provider with the above information. If this problem continues, IPNs may be disabled for your account. 

> Thank you for your prompt attention to this issue.

**Comment by andris-sevcenko** [comment]
This plugin provides three different gateways. Which one are you using?

**Comment by 23d1** [comment]
PayPal Express.

Edit:
We seem to be getting these for every order actually.
It's the redirect back to the confirmed/paid order page.

**Comment by andris-sevcenko** [comment]
Is it possible to send your logs over to support@craftcms.com referencing this issue?

**Comment by amphibian** [comment]
I'm now getting these same notifications from PayPal as well, though I have successful payments coming through before October 7th. PayPal Express.

**Comment by 23d1** [comment]
@andris-sevcenko would sending over slack work? If I email, should I include the issue description?

I actually can’t see anything relevant in the web.log… Only an old test order.
I should also add that IPNs are disabled at PayPal, so very strange that we're receiving these warnings (might have been disabled by PayPal, but either way, it's not something we use unless it's used by Craft somehow).

@amphibian very odd, right? We have the last successful order come through on October 8th.

**Comment by andris-sevcenko** [comment]
Okay, running `composer update` should update `craftcms/commerce-omnipay` to 1.0.2 and resolve this issue for you, guys.
