### ISSUE TITLE
PayPal Pro and PSD2 / SCA support

### ISSUE THREAD

**Issue by rogerdawkins** [craftcms/commerce-paypal#15]
I have setup a charity website including a simple online store using Craft Commerce 2 and the PayPal Pro gateway.

With the upcoming European regulation changes, it means that all sites will need to support the PSD2 requirements and Strong Customer Authentication (SCA). The changes will be compulsory from 14th September 2019.

Are there any plans for the PayPal Pro element of this gateway to support the changes? In a PayPal email it suggested using a free authentication merchant plug-in from CardinalCommerce to activate 3D-Secure but I think that then needs to be integrated with the gateway.

In the meantime I can switch my client to PayPal Express to use a hosted payment form.

**Comment by andris-sevcenko** [comment]
We built the plugin according to their documentation and our experience, but we are unable to ensure that it meets specific countries/area regulatory requirements at the moment.

We have reached out to cardinal commerce to figure out a way we can get listed in their "paypal 3d secure registration page", and anything we need to do to the plugin to get ready for the regulations.
