### ISSUE TITLE
Passing Address to PayPal Express

### ISSUE THREAD

**Issue by bymayo** [craftcms/commerce-paypal#18]
We have had a client say that either the shipping/billing address isn't being passed to PayPal Express when their customers choose this payment method.

Is there something I'm missing to pass this information over?

We've ticked on `Should commerce send cart information to gateway when making transactions.` but this has made no difference.

They've said by not passing this information across to PayPal they don't qualify for PayPal Seller Protection

**Comment by cole007** [comment]
Also experiencing this issue

**Comment by joshangell** [comment]
Me too - it also means that the owner of the site isn’t covered under Seller Protection as I just found out the hard way ... in our situation a customer claimed they never received the package, and PayPal refunded them in full despite the site owner having sent it.

It would be really handy to have the address sent over as well so that the site owners get the Seller Protection cover.

You can see the terms that affect this here at point 3 under the "Basic requirements" heading: https://www.paypal.com/us/webapps/mpp/ua/useragreement-full#seller-protection

**Comment by tom-c** [comment]
Same here, client wants PayPal enabled and they're shipping expensive items so this is critical for us.

**Comment by rob-c-baker** [comment]
Same again here too.

**Comment by nfourtythree** [comment]
Hey all

Please check out the new PayPal Checkout gateway that is soon to be live on the plugin store. https://github.com/craftcms/commerce-paypal-checkout

This uses the latest integration provided by PayPal called "Checkout". This has much better support for passing customers information to PayPal and restricting their ability to change it.

We will be looking to continue updating and adding functionality to that plugin as PayPal has deprecated/is killing off PayPal Express.

**Comment by RitterKnightCreative** [comment]
Upgrading a client's old Commerce 1 install to 3 and running into the same issue. This worked just fine on Commerce 1, not sure what changed with the upgraded versions? 

@nfourtythree Looks like the checkout version you mention above is more modern, however if I select the "Debit or Credit Card" button, it appears Commerce is still not passing in any of the billing details? 

If I use the PayPal option, it seems to pass more details, but state, email address, and First / Last Name are still not going in.

I've also ruled out any template issues, just using the templates that come with Commerce as a test.

**Comment by nfourtythree** [comment]
Hi @RitterKnightCreative 

I have just looked into the Checkout API and it appears we are able to pass payer details. I have created a new issue over on that repo: https://github.com/craftcms/commerce-paypal-checkout/issues/11

Please post any questions/comments over there to continue the discussion.

It is unlikely that we will be making any further updates to this plugin.

Thanks.
