### ISSUE TITLE
PayPal redirect back url results in a 404

### ISSUE THREAD

**Issue by davidhellmann** [craftcms/commerce-paypal#2]
I use the Paypal Gateway works all fine but the redirect from Paypal is this: 
`example.com/index.php/actions/commerce/payments/complete-payment?commerceTransactionHash=XXXXXXXXXXXXXXXXXXXXXXXXXXXX&token=EC-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX`

I'm a bit confused where it comes from and how we can update it.

Any Ideas whats going wrong here? It's a bit important :/

**Comment by andris-sevcenko** [comment]
I'll assume you're talking about `example.com`, which is somewhere in your config, probably? What domain are you using to access your test site?

Omnipay gateways do not make assumptions about the hostname, they just use whatever Craft tells them the hostname is. (https://github.com/craftcms/commerce-omnipay/blob/master/src/base/Gateway.php#L507-L508)

**Comment by internetztube** [comment]
The problem is not the url it self. The domain and the path are correct. The problem is that the generated action url throws an http 404 error.
For me it looks as if the action would not be registered.

**Comment by andris-sevcenko** [comment]
Just to be clear - you have seen https://github.com/craftcms/commerce-paypal#important and have changed the value of the `tokenParam` config setting?

**Comment by internetztube** [comment]
Thank you for your efforts. I have ended up building the checkout exactly as it is in the demo. Works now. Thank you and sorry.

**Comment by andris-sevcenko** [comment]
@internetztube no trouble at all!
