### ISSUE TITLE
Environment based Sandbox

### ISSUE THREAD

**Issue by kaspar-allenbach** [craftcms/commerce-paypal#21]
You know what would be really cool?
The ability to set the Test Mode automaticaly via environement config.

Something like this: 

```
'dev' => [
   'paypalTestMode' => true,
],
'production' => [
   'paypalTestMode' => false,
]
```

Or maybe a listener who reacts to the craft dev mode config: `'devMode' => true,`

**Comment by andris-sevcenko** [comment]
You can already use a separate config file for that (https://docs.craftcms.com/commerce/v2/gateway-config.html) and you can use `'testMode' => (bool) getenv('PAYPAL_TEST_MODE')` inside that config file.
