### ISSUE TITLE
Return URL does not route to "commerce/payments/complete-payment"

### ISSUE THREAD

**Issue by Anubarak** [craftcms/commerce-paypal#23]
I'm not fully into omnipay so maybe I did something wrong. I installed the plugin and filled the settings, but I'm unable to make a payment. I'm not entirely sure how I'm supposed to fix the returnUrl in your JS or even if I'm supposed to use the JS there.

[This one](https://github.com/craftcms/commerce-paypal/blob/master/src/resources/js/paymentForm.js#L39)

Returns an object with the property `returnUrl` and this is something like

```
"https://example.dev/index.php?p=admin/actions/commerce/payments/complete-payment&commerceTransactionHash=38e9d950e911ca849435ee47d52bda8d&token=EC-00807207G21606545&PayerID=XXXXXX"
```

The issue is; this is not dealed as "action" request as per https://github.com/craftcms/cms/blob/develop/src/web/Request.php#L1264 the URL contains a "token" paramter so Craft won't accept it as an action request. 
Is there a suggested work around for this? I could either change the token param or change that JS and use a custom one. I've tried to somehow route directly to the controller without an action param or include the route in my custom plugin but that does not seem to be clean

**Comment by nfourtythree** [comment]
Hi @Anubarak 

Have you taken the [following steps from the readme](https://github.com/craftcms/commerce-paypal#important)?

Also just as an FYI we have a new [PayPal gateway](https://github.com/craftcms/commerce-paypal-checkout) that uses the currently support PayPal Checkout.

Thanks.

**Comment by Anubarak** [comment]
Oh, thank you very much for your fast reply and I'm really sorry for my mistake. I totally oversaw it.
