### ISSUE TITLE
Abandoned but no replacement?

### ISSUE THREAD

**Issue by boboldehampsink** [craftcms/commerce-paypal#26]
Composer says "Package craftcms/commerce-paypal is abandoned, you should avoid using it. Use craftcms/commerce-paypal-checkout instead."

But commerce-paypal-checkout doesn't contain support for Paypal Express, for example. Is this really abandoned?

**Comment by nfourtythree** [comment]
Hi @boboldehampsink 

The reason for this is that PayPal themselves have state that the PayPal Express checkout API is deprecated as of 1st January 2017. Their recommendation is to switch to the PayPal Checkout integration.

This is what the other plugin integrates.

Hope this helps, thanks!

**Comment by boboldehampsink** [comment]
Hi @nfourtythree, thanks. That clarifies it. Might want to add this in the readme?

**Comment by boboldehampsink** [comment]
Went ahead and did that: https://github.com/craftcms/commerce-paypal/pull/27

**Comment by boboldehampsink** [comment]
Hey @nfourtythree I can't seem to find paypal's deprecation notice anywhere, would you have a link for that?

**Comment by nfourtythree** [comment]
Hi @boboldehampsink 

Sure, here is the link: https://developer.paypal.com/docs/archive/express-checkout/ec-api-flow/

![](https://p191.p3.n0.cdn.getcloudapp.com/items/jkuD69GX/Screenshot%202020-10-30%20at%2008.34.18.png?v=5d1c83ad63c0e86e38367fc5c0a6192c)
