### ISSUE TITLE
Error Submitting PayPal Rest Token

### ISSUE THREAD

**Issue by magnessjo** [craftcms/commerce-paypal#3]
The paymentForm model is returning errors when I do an Ajax submission to the Payments Controller in Commerce.  I've tracked the issue to the rules in PayPalRestPaymentForm model class.  

My understanding is that the token being set would modify the rule settings (similar to Stripe plugin payment model) so that the parent (CreditCardPaymentForm) rules would not apply.  Basically, the token validates those attributes (firstName, lastName, etc).  

Example Payment Form Object: 

(
    [cardReference] => 
    [firstName] => 
    [lastName] => 
    [number] => 
    [month] => 
    [year] => 
    [cvv] => 
    [token] => EC-8M4794274U743332C
    [expiry] => 
    [threeDSecure] => 
    [_errors:yii\base\Model:private] => Array
        (
            [firstName] => Array
                (
                    [0] => First Name cannot be blank.
                )

            [lastName] => Array
                (
                    [0] => Last Name cannot be blank.
                )

            [month] => Array
                (
                    [0] => Month cannot be blank.
                )

            [year] => Array
                (
                    [0] => Year cannot be blank.
                )

            [cvv] => Array
                (
                    [0] => Cvv cannot be blank.
                )

            [number] => Array
                (
                    [0] => Number cannot be blank.
                )

        )

**Comment by andris-sevcenko** [comment]
How are you getting that token and what does it represent?

**Comment by magnessjo** [comment]
@andris-sevcenko,

  I left the computer for a few hours so I’m sorry if this answer isn’t as concise.  I will update my response when I get home if it’s not enough information for you to go on.  

  I am getting the token from the on authorize function of the pay pal Client side API.  https://developer.paypal.com/docs/integration/direct/express-checkout/integration-jsv4/client-side-REST-integration/

**Comment by andris-sevcenko** [comment]
If you’re implementing the Express Checkout payment flow, you should be using the Express Checkout gateway that is included with this plugin.
