### ISSUE TITLE
Paypal Pay in 3

### ISSUE THREAD

**Issue by iamtompickering** [craftcms/commerce-paypal#31]
### Description
Wondering if it is at all possible to enable PayPals 'Pay in 3' option to this plugin? 

Is this something that needs to be added to the plugin or is it simply the case of enabling something within your PayPal account?

Any info you could give on this would be appreciated!

**Comment by iamtompickering** [comment]
Just giving this a nudge, it would be good to get an answer to this please.

**Comment by nfourtythree** [comment]
Hi @iamtompickering 

This is now possible with the PayPal Checkout plugin: https://github.com/craftcms/commerce-paypal-checkout/issues/73

As [mentioned in the README](https://github.com/craftcms/commerce-paypal#deprecation-notice) of this version of the PayPal integration, it is now deprecated and will not be seeing any new features added.

Thanks.
