### ISSUE TITLE
Add ability to specify additional configuration for PayPal Express button

### ISSUE THREAD

**Issue by ackwell** [craftcms/commerce-paypal#5]
When using the PayPal Express payment gateway, the PayPal button generated by `resources/js/paymentForm.js` has no means to customise the styling of the button itself (e.g. via the `style:` prop).

While it's possible to work around this by making a non-vendor copy of the init code, I'm hesitant to do so in case changes are made to the underlying systems it's leaning on.

Apologies in advance if I've totally missed the option somewhere.

**Comment by j-greig** [comment]
Also very keen to have this option 👍 

In the meantime, a way to disable the paymentForm.js from being loaded would be great, maybe there's an existing way to achieve this?

**Comment by andris-sevcenko** [comment]
@j-greig You can always just not use `gateway.getPaymentForm()`, which includes the `paymentForm.js`, but roll your own.

@ackwell this approach also will fix your issue.
