### ISSUE TITLE
Correlation id: unknown

### ISSUE THREAD

**Issue by olsp** [craftcms/commerce-paypal#7]
I try to get PayPal Express running but have quite some difficulties. I use the default templates for testing and can get through the whole checkout and payment process, but then PayPal closes and in the console I see the following

```
http.js:114 Paypal Uncaught Error: Request to post http://xxx.local/index.php?p=actions/commerce/payments/complete-payment&commerceTransactionHash=xxx&token=xxx&PayerID=xxx failed with 400 error. 
Correlation id: unknown   
{"error": "Es ist nicht möglich, Ihre Dateneingabe zu prüfen."}
```
The error message can be translated to: It's not possible to check your data input.

In my Craft config, I changed the token name, as described here: https://github.com/craftcms/commerce-paypal
And also disabled CSRF.

Any ideas what the reason for this could be?

**Comment by andris-sevcenko** [comment]
This was resolved over email. CSRF was not correctly disabled.

**Comment by j-greig** [comment]
I have the same issue (using default checkout template from the repo) and can only resolve it by setting `'enableCsrfProtection' => false,` in the site config. Is there a better way that's specific to the payment form?
