### ISSUE TITLE
Paypal Express configuration

### ISSUE THREAD

**Issue by howells** [craftcms/commerce-paypal#8]
I feel like I'm going mad here, but I can't figure out how to get my PayPal API details for PayPal Express and I'm not sure where to turn for support.

In my PayPal Express config I can only see values for "Live Account" and "AccessToken" - not API Username, etc. which is expected in Craft config: https://cl.ly/f7ba5faa01c9

Any ideas?

**Comment by andris-sevcenko** [comment]
Those are Braintree SDK credentials. For PayPal Express you need NVP/SOAP credentials: https://developer.paypal.com/docs/classic/api/apiCredentials/#types-of-credentials

**Comment by howells** [comment]
I see - sorry, Paypal makes finding the right credentials incredibly hard. On my account I'm told that these are deprecated; is there any plans to update for Braintree, which I guess is the new version?

**Comment by andris-sevcenko** [comment]
@howells there definitely are plans, but there is no timeline yet, as there are quite a few things on our plate. I'll make a GH issue so that this does not get lost.

For the record, I agree, however, that it's incredibly frustrating finding the right credentials.
