### ISSUE TITLE
Update to PayPal Checkout

### ISSUE THREAD

**Issue by andris-sevcenko** [craftcms/commerce-paypal#9]
Paypal Express is deprecated as of 01.012017.

The suggested path is to update to PayPal Checkout (https://developer.paypal.com/docs/checkout/integrate/#)

**Comment by keyurshah** [comment]
Hello!

Wondering the status of this. Need to integrate PayPal express checkout and not sure which method we can use with craft commerce pro.

**Comment by lukeholder** [comment]
@keyurshah  We are working on supporting the latest paypal checkout UX - We can't give you a timeline at the moment. In the meantime I believe you can use any of the existing gateways and they should still work.

**Comment by lukeholder** [comment]
subscribe to this issue to keep updated.

**Comment by julienmarie** [comment]
Any news on this? It's been more than a year

**Comment by nfourtythree** [comment]
Hey @julienmarie 

You timed this question pretty perfectly! We have just pushed an alpha version of the [PayPal Checkout gateway](https://github.com/craftcms/commerce-paypal-checkout) and are looking for testers!

It would be great if you could be one of those testers and let us know your feedback over on that repository.

**Comment by nfourtythree** [comment]
We have split out the Checkout gateway into its own repository: https://github.com/craftcms/commerce-paypal-checkout

**Comment by keyurshah** [comment]
That's great news! Will this provide the Express style checkout where they login into Paypal and then they return back to the site to finish address and shipping selection?

**Comment by nfourtythree** [comment]
Hey @keyurshah currently this is implemented in the same way the Express work on this plugin. Which is just to take payment at the end of the checkout process.

Now we have the specific PayPal Checkout repo we can look at enhancements and how it could work. Please feel free to open a feature request issue on that repository.

Thanks
